### ISSUE TITLE
Serve REST APIs from a file system

### ISSUE THREAD

**Issue by tholthamizh** [tholthamizh/tholthamizhpadhangal#2]
The rest APIs serve data from files loaded in the classpath. This needs to be served from a configured location in file system.

**Comment by tholthamizh** [comment]
@xadhix

**Comment by xadhix** [comment]
What do you mean by "Serve REST APIs from a file system"

**Comment by tholthamizh** [comment]
At present, the data is stored in this location **tholthamizhpadhangal/play/thol/public/data/**. While building, the public directory gets packaged within the play service jar. If some modifications need to be done in the list of words or their description, build upgrade is the only way. The admin should be able to add/delete/modify the existing words without re-deploying or restarting the service.

```
GET     /api/words          controllers.Assets.at(path="/public/data", file = "words.json")     

GET     /api/words/:word    controllers.Assets.at(path="/public/data/words", word:String)           
```

This is how these two APIs are implemented where controllers.Assets is a controller comes packaged with play. It reads the data from classpath and returns the response.

What needs to be done is to write a new controller which reads a specific location (e.g /var/data/thol) in the file system and returns the response.

**Comment by tholthamizh** [comment]
Created develop branch. Lets commit the changes in develop.

**Comment by tholthamizh** [comment]
@xadhix Sorry.. I had to fix this..
